In [6]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

v1 = torch.tensor([1, 2, 3]).to(device)
print(v1)
v2 = torch.tensor([3, 2, 1])
print(v2)
v3 = v1.to("cpu") + v2
print(v3)
print(v1)

tensor([1, 2, 3], device='cuda:0')
tensor([3, 2, 1])
tensor([4, 4, 4])
tensor([1, 2, 3], device='cuda:0')


: 